---
apiVersion: v1
kind: Pod
metadata:
  name: kea-dhcp4
spec:
  restartPolicy: Always
  hostNetwork: true
  containers:
  - name: kea-dhcp4
    image: randomcoww/kea:latest
    args:
    - kea-dhcp4
    env:
    - name: CONFIG
      value: |
        {
          "Dhcp4": {
            "valid-lifetime": 300,
            "interfaces-config": {
              "interfaces": [
                "*"
              ]
            },
            "subnet4": [
              {
                "subnet": "192.168.62.0/23",
                "option-data": [
                  {
                    "name": "routers",
                    "data": "192.168.62.240"
                  },
                  {
                    "name": "domain-name-servers",
                    "data": "192.168.62.230,8.8.8.8",
                    "csv-format": true
                  }
                ],
                "pools": [
                  {
                    "pool": "192.168.62.32/27"
                  }
                ],
                "reservations": [

                ]
              },
              {
                "subnet": "192.168.30.0/23",
                "pools": [
                  {
                    "pool": "192.168.30.32/27"
                  }
                ]
              }
            ],
            "dhcp-ddns": {
              "enable-updates": true,
              "qualifying-suffix": "loc",
              "override-client-update": true,
              "override-no-update": true,
              "replace-client-name": "when-not-present"
            }
          }
        }
  - name: kea-dhcp-ddns
    image: randomcoww/kea:latest
    args:
    - kea-dhcp-ddns
    env:
    - name: CONFIG
      value: |
        {
          "DhcpDdns": {
            "ip-address": "127.0.0.1",
            "port": 53001,
            "dns-server-timeout": 100,
            "ncr-protocol": "UDP",
            "ncr-format": "JSON",
            "tsig-keys": [
              {
                "name": "update_key",
                "algorithm": "HMAC-SHA512",
                "secret": "bvX8jbbuosgA4IjLFH1KUw=="
              }
            ],
            "forward-ddns": {
              "ddns-domains": [
                {
                  "name": "loc.",
                  "key-name": "update_key",
                  "dns-servers": [
                    {
                      "ip-address": "192.168.62.230",
                      "port": 53530
                    }
                  ]
                }
              ]
            },
            "reverse-ddns": {
              "ddns-domains": [

              ]
            }
          }
        }
